import Head from 'next/head'
import Store from './Store';
import globals from "../Globals.json";
import axios from 'axios';
import ICardProducts from '@/Interface/ICardProducts';


const base_url = "https://mks-challenge-api-frontend.herokuapp.com"


export default function Home({ products }: any) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Store products={products} />
    </>
  )
}

export const getStaticProps = async () => {

  try {
    const { data } = await axios.get(`${base_url}/${globals.api.products}?page=1&rows=8&sortBy=id&orderBy=ASC`);

    const products: ICardProducts[] = await data.products

    return { props: { products }, revalidate: 10, };

  } catch (error) {
    console.log(error);
  }

}