import Head from 'next/head'
import Store from '../components/Store';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';
import { calculateTotals, getProductsItems } from '../features/cart/cartSlice';
import { AppDispatch } from '@/store';
import Cart from '@/components/Cart';


export default function Home() {
  const { cartProducts, isLoading } = useSelector((store: any) => store.cart)
  const dispatch = useDispatch<AppDispatch>();


  useEffect(() => {
    dispatch(getProductsItems());
  }, [])

  useEffect(() => {
    dispatch(calculateTotals());
  }, [cartProducts]);

  if (isLoading) {
    return (
      <div><h1>Loading...</h1></div>
    )
  }

  return (
    <>
      <Head>
        <title>MKS sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Store />
      <Cart />
      <Footer />
    </>
  )
}
